services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: raffy
      POSTGRES_USER: raffy
      POSTGRES_PASSWORD: raffy
    ports:
      - "5432:5432"
    volumes:
      - raffy_db:/var/lib/postgresql/data

volumes:
  raffy_db:
